### ISSUE TITLE
Gradient type radios not working in Safari

### ISSUE THREAD

**Issue by vicbergquist** [vicbergquist/shapy#10]
**Describe the bug**
It doesn't work changing the gradient type radio buttons (linear vs radial, repeat vs. no-repeat

**To Reproduce**
1. Go to the generator using the safari browser
2. Click on radial or linear gradient
3. Preview does not update

**Expected behavior**
Gradient type should change. Works in Firefox and chrome.
Checked if the @input event was at fault, but an event is fired.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser [e.g. chrome, safari] Safari
 - Version [e.g. 22] 12.0.1

**Smartphone (please complete the following information):**

**Additional context**

**Comment by MichaelE1** [comment]
Are you sure the @ input event is working? I used @ change and that fixed it on Safari (desktop).

**Comment by vicbergquist** [comment]
Yeah I tried binding it to a method and the @input fired. If it works with @change I’ll fix it 😊 Thank you!
