### ISSUE TITLE
Copy CSS code button

### ISSUE THREAD

**Issue by vicbergquist** [vicbergquist/shapy#19]
**Is your feature request related to a problem? Please describe.**
A button to copy the CSS code generated

**Describe the solution you'd like**
Add a button next the list or somewhere to copy the gradients that have been added to the canvas.

**Describe alternatives you've considered**

**Additional context**

**Comment by MichaelE1** [comment]
This one can probably be closed? (https://github.com/vicbergquist/shapy/commit/b2ee9cf2d052e935fc352852be5d06b6c75b84e9)

Nicely done btw :smiley_cat:

**Comment by vicbergquist** [comment]
Oh yes, totally forgot! Thank you!
